// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// SIRsolver
Rcpp::DataFrame SIRsolver(double density_init, double f, double lambda, double delta, double b1, double b2, double c1, double c2, double r1, double r2, double r3, double r4, double sigma, int maxt_eco, int maxt_evo, double alpha_init, double eul_eco, double eul_evo);
RcppExport SEXP _SIRImperfectVaccination_SIRsolver(SEXP density_initSEXP, SEXP fSEXP, SEXP lambdaSEXP, SEXP deltaSEXP, SEXP b1SEXP, SEXP b2SEXP, SEXP c1SEXP, SEXP c2SEXP, SEXP r1SEXP, SEXP r2SEXP, SEXP r3SEXP, SEXP r4SEXP, SEXP sigmaSEXP, SEXP maxt_ecoSEXP, SEXP maxt_evoSEXP, SEXP alpha_initSEXP, SEXP eul_ecoSEXP, SEXP eul_evoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type density_init(density_initSEXP);
    Rcpp::traits::input_parameter< double >::type f(fSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< double >::type b1(b1SEXP);
    Rcpp::traits::input_parameter< double >::type b2(b2SEXP);
    Rcpp::traits::input_parameter< double >::type c1(c1SEXP);
    Rcpp::traits::input_parameter< double >::type c2(c2SEXP);
    Rcpp::traits::input_parameter< double >::type r1(r1SEXP);
    Rcpp::traits::input_parameter< double >::type r2(r2SEXP);
    Rcpp::traits::input_parameter< double >::type r3(r3SEXP);
    Rcpp::traits::input_parameter< double >::type r4(r4SEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< int >::type maxt_eco(maxt_ecoSEXP);
    Rcpp::traits::input_parameter< int >::type maxt_evo(maxt_evoSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_init(alpha_initSEXP);
    Rcpp::traits::input_parameter< double >::type eul_eco(eul_ecoSEXP);
    Rcpp::traits::input_parameter< double >::type eul_evo(eul_evoSEXP);
    rcpp_result_gen = Rcpp::wrap(SIRsolver(density_init, f, lambda, delta, b1, b2, c1, c2, r1, r2, r3, r4, sigma, maxt_eco, maxt_evo, alpha_init, eul_eco, eul_evo));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SIRImperfectVaccination_SIRsolver", (DL_FUNC) &_SIRImperfectVaccination_SIRsolver, 18},
    {NULL, NULL, 0}
};

RcppExport void R_init_SIRImperfectVaccination(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
