# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Run a single SIR simulation a la eqns. 6, 7 from Gandon
#' et al 2001 Nature to optimize virulence in the face of
#' different medical interventions
#' @param density_init initial numbers (equal for susceptible and infected) (floating-point)
#' @param f fraction vaccinated (floating-point)
#' @param lambda birth rate (floating-point)
#' @param delta parasite-independent mortality rate (floating-point)
#' @param b1 intercept of trade-off curve virulence-induced mortality vs transmission (floating-point)
#' @param b2 power of trade-off curve virulence-induced mortality vs transmission (floating-point)
#' @param c1 intercept of trade-off curve virulence-induced mortality vs recovery (floating-point)
#' @param c2 power of trade-off curve virulence-induced mortality vs recovery (floating-point)
#' @param r1 anti-infection immunity (floating-point value)
#' @param r2 anti-growth rate immunity (floating-point value)
#' @param r3 transmission-blocking immunity (floating-point value)
#' @param r4 anti-toxin immunity (floating-point value)
#' @return A \code{list} that contains the values of the equilibrium 
#'     densities x, x', y, y' and virulence alpha
#' @examples
#'     # test run of a simulation
#'     list.result <- SIRsolver(
#'                         density_init=100,
#'                         f=0.2,
#'                         lambda=25,
#'                         delta=1,
#'                         b1=1,
#'                         b2=0.5,
#'                         c1=1,
#'                         c2=0.2,
#'                         r1=0,
#'                         r2=0,
#'                         r3=0,
#'                         r4=0)
#'
#' @export 
SIRsolver <- function(density_init = 100, f = 0.3, lambda = 25, delta = 1, b1 = 1, b2 = 0.5, c1 = 1, c2 = 0.2, r1 = 0.0, r2 = 0.0, r3 = 0.0, r4 = 0.0) {
    .Call(`_SIRImperfectVaccination_SIRsolver`, density_init, f, lambda, delta, b1, b2, c1, c2, r1, r2, r3, r4)
}

